# Base image [cite: 11]
FROM python:3.9-slim-buster

# Set working directory
WORKDIR /app

# Copy requirements file and install dependencies [cite: 11]
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY ./app /app

# Expose port 7000 [cite: 11]
EXPOSE 7000

# Entrypoint to run uvicorn [cite: 11]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]